name: ielect
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  excel: ^4.0.3
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.8
  file_picker: ^8.0.0+1
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.1

  cloud_firestore: ^4.16.1
  email_validator: ^2.1.17
  shared_preferences: ^2.2.3
  mailer: ^6.1.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.2.2+4
  provider: ^5.0.0
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^17.1.2
  flutter_staggered_grid_view: ^0.7.0
  swipable_stack: ^2.0.0
  barcode_widget: ^2.0.4
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1
  timer_count_down: ^2.2.2
  pinput: ^4.0.0

  google_fonts: ^6.2.1
  card_swiper: ^3.0.1
  flow_builder: ^0.1.0
  http: ^1.2.1
  image: ^4.2.0
  cached_network_image: ^3.3.1





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/image/
    - .env

  uses-material-design: true
